### PR TITLE
Switch to log crate

### LINKED ISSUE #184: When resolving to stdout do not display status
**Describe the bug**
When the output is stdout, the status lines (example below) will break any kind of stream processing, such as passing it to `jq`.

example:
```
✔ SemConv registry loaded (111 files)
✔ No policy found
✔ SemConv registry resolved
```

**To Reproduce**
1. Run `weaver registry resolve -f json | jq .`
2. watch it fail because of the status printed at the beginning

**Expected behavior**
The resolve output should be in the correct format, free of any status outputs.  

**Additional context**
These statuses are nice if we are outputting to a file or if they were on stderr.

### PR DESCRIPTION
**Pull request by jerbly**
All logging and diagnostics now go to `stderr`. Override diagnostics with `--diagnostic-stdout`.

Fixes #184 

This achieves everything but the animated loading lines using `log` and `env_logger` which are basically the rust standard. This means we no longer pass the logger around and just use standard log macros `info!("did a thing")` .
To keep the look and feel of paris, we import the formatting functions and then do things like this: `warn!("{}", colorize_string("<b><green>TEST"));`. For the most common there are now simple functions like: `log_success()`, `log_error()` etc.

The separation of `stderr` and `stdout` also means we don't really need `--quiet` anymore. I've left it in though. I've also changed the `ExitDirective` so you can exit a command positively via an `Ok()` and still print out any collected warnings.

### CODE REVIEW

**Review by jsuereth — APPROVED** [review]

File: crates/weaver_forge/src/debug.rs [hunk 1]
```diff
@@ -111,7 +110,10 @@ mod tests {
 
     #[test]
     fn test_print_dedup_errors() {
-        let logger = weaver_common::TestLogger::new();
+        // Setup TestLog to capture log messages and keep a reference to it
+        let test_log = weaver_common::TestLog::new();
+        test_log.clone().init().expect("Failed to init logger");
```
Comment (lquerel) [inline crates/weaver_forge/src/debug.rs:115]: This split between the constructor and the init method seems really error-prone to me. Couldn’t we have a constructor that performs the initialization? Otherwise, there’s a high chance someone will misuse the logger.

**Review by lquerel — APPROVED** [review]
I made a comment about the logger initialization, but otherwise, it looks good to me.

File: crates/weaver_forge/src/debug.rs (hunk 1 above)
Comment (jerbly) [reply crates/weaver_forge/src/debug.rs:115]: Fixed in #727
