### PR TITLE
Fix #750 - Dual registry resolves incorrectly

### LINKED ISSUE #750: Dual registry resolves incorrectly
**Describe the bug**
The resolver returns strange results with duplicated and/or missing attributes. Tested with the released version 0.15.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `weaver registry resolve -r data/multi-registry/custom_registry`
2. Note the incorrect resolved output:
```yaml
groups:
- id: shared.attributes
  type: attribute_group
  brief: Attributes shared between our signals.
  attributes:
  - name: error.type
    type: string
    brief: The error type.
    examples: Ex
    requirement_level: required
    stability: stable
  - name: auction.name
    type: string
    brief: |
      The name of the auction
    examples:
    - Fish for sale
    requirement_level: recommended
    stability: stable
  span_kind: null
  events: []
  metric_name: null
  instrument: null
  unit: null
  name: null
  lineage:
    provenance:
      registry_id: acme
      path: data/multi-registry/custom_registry/custom_registry.yaml
- id: metric.auction.bid.count
  type: metric
  brief: Count of all bids we've seen
  stability: stable
  attributes:
  - name: auction.name
    type: string
    brief: |
      The name of the auction
    examples:
    - Fish for sale
    requirement_level: recommended
    stability: stable
  - name: auction.id
    type: int
    brief: |
      The id of the auction.
    requirement_level: recommended
    stability: stable
  - name: auction.id
    type: int
    brief: |
      The id of the auction.
    requirement_level: required
    stability: stable
  span_kind: null
  events: []
  metric_name: auction.bid.count
  instrument: counter
  unit: '{bid}'
  name: null
  lineage:
    provenance:
      registry_id: acme
      path: data/multi-registry/custom_registry/custom_registry.yaml
    attributes:
      auction.id:
        source_group: shared.attributes
        inherited_fields:
        - brief
        - note
        - stability
        locally_overridden_fields:
        - requirement_level
      auction.name:
        source_group: shared.attributes
        inherited_fields:
        - brief
        - examples
        - note
        - stability
        locally_overridden_fields:
        - requirement_level
      error.type:
        source_group: otel.registry
        inherited_fields:
        - brief
        - examples
        - note
        - stability
        locally_overridden_fields:
        - requirement_level
``` 

**Expected behavior**
In the attribute_group and metric it should have: `error.type`, `auction.id` and `auction.name`. Instead we're missing `auction.id` from the attribute_group and we have `auction.id` duplicated in the metric and `error.type` is missing! Note that the `test_multi_registry()` unit test is passing.

### PR DESCRIPTION
**Pull request by lquerel**
This bug does not appear when:
- resolving a single registry
- resolving two registries without calling `gc_unreferenced_attribute_refs`

When two registries are involved and `gc_unreferenced_attribute_refs` is called (i.e., without the `--include-unreferenced` parameter), resolution sometimes succeeds and sometimes fails. The intermittent success occurs because `HashMap` ordering in Rust is random, and the small number of elements in the test frequently resulted in the expected outcome. Additionally, the initial test was insufficiently robust.

The source of the bug lies in the `AttributeCatalog::gc_unreferenced_attribute_refs` method, which returned the correct mapping but did not internally modify the catalog as intended... Pretty bad!

Closes #750

### CODE REVIEW

File: crates/weaver_resolver/src/lib.rs [hunk 1]
```diff
@@ -492,6 +495,10 @@ mod tests {
                             }
                         }
                     }
+                    assert_eq!(metric.attributes.len(), 3);
+                    assert!(attr_names.contains("auction.name"));
+                    assert!(attr_names.contains("auction.id"));
+                    assert!(attr_names.contains("error.type"));
```
Comment (lquerel) [inline crates/weaver_resolver/src/lib.rs:501]: The previous version of this was definitely not strong enough...

**Review by jsuereth — APPROVED** [review]
