### PR TITLE
Fix panic in update-markdown.  Uses errors and return to signal failu…

### LINKED ISSUE #960: Panic in Weaver
**Describe the bug**
Weaver panics.

**To Reproduce**
1. Check out commit `a3adbb3b59cfdfa2e2c75b7bdbc3a1cd22510836` from https://github.com/open-telemetry/semantic-conventions
2. Run `make table-check`

**Expected behavior**
Weaver to successfully complete the check and compliment me for the awesomeness of the change.

**Additional context**
I am wildly speculating here, but Weaver may be emotionally attached to the `peer.service` attribute of semconvs.

### PR DESCRIPTION
**Pull request by jsuereth**
…re now.

Fixes #960

### CODE REVIEW

File: src/registry/update_markdown.rs [hunk 1]
```diff
@@ -19,6 +20,17 @@ use weaver_forge::TemplateEngine;
 use weaver_semconv::registry_repo::RegistryRepo;
 use weaver_semconv_gen::{update_markdown, SnippetGenerator};
 
+#[derive(thiserror::Error, Debug, serde::Serialize, Diagnostic)]
+enum UpdateMarkdownError {
+    /// The update-markdown command found differences in dry-run.
+    #[error("The update-markdown command found differences in dry-run.")]
+    MarkdownNotUpToDate,
+
+    /// The update-markdown command found differences in dry-run.
```
Comment (jerbly) [inline src/registry/update_markdown.rs]: Wrong doc comment?

**Comment by jerbly** [comment]
@jsuereth - minor doc typo to fix... also wondering if we have test cases for these failure scenarios?

File: src/registry/update_markdown.rs (hunk 1 above)
Comment (jsuereth) [reply src/registry/update_markdown.rs]: fixed
